In [1]:
import numpy as np
import pandas as pd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

%pwd

'/home/cseadmin/dz/Torch-MTS/data/METRLA'

In [6]:
store=pd.HDFStore("./metr-la.h5", "r")

store.keys()

['/df']

In [7]:
df_data=store["df"]

df_data

773869     767541     767542     717447     717446  \
2012-03-01 00:00:00  64.375000  67.625000  67.125000  61.500000  66.875000   
2012-03-01 00:05:00  62.666667  68.555556  65.444444  62.444444  64.444444   
2012-03-01 00:10:00  64.000000  63.750000  60.000000  59.000000  66.500000   
2012-03-01 00:15:00   0.000000   0.000000   0.000000   0.000000   0.000000   
2012-03-01 00:20:00   0.000000   0.000000   0.000000   0.000000   0.000000   
...                        ...        ...        ...        ...        ...   
2012-06-27 23:35:00  65.000000  65.888889  68.555556  61.666667   0.000000   
2012-06-27 23:40:00  61.375000  65.625000  66.500000  62.750000   0.000000   
2012-06-27 23:45:00  67.000000  59.666667  69.555556  61.000000   0.000000   
2012-06-27 23:50:00  66.750000  62.250000  66.000000  59.625000   0.000000   
2012-06-27 23:55:00  65.111111  66.888889  66.777778  61.222222   0.000000   

                        717445     773062     767620     737529     717816  \
2012-03-01 00:00:00  68.750000  65.125000  67.125000  59.625000  62.750000   
2012-03-01 00:05:00  68.111111  65.000000  65.000000  57.444444  63.333333   
2012-03-01 00:10:00  66.250000  64.500000  64.250000  63.875000  65.375000   
2012-03-01 00:15:00   0.000000   0.000000   0.000000   0.000000   0.000000   
2012-03-01 00:20:00   0.000000   0.000000   0.000000   0.000000   0.000000   
...                        ...        ...        ...        ...        ...   
2012-06-27 23:35:00  54.555556  62.444444  63.333333  59.222222  65.333333   
2012-06-27 23:40:00  50.500000  62.000000  67.000000  65.250000  67.125000   
2012-06-27 23:45:00  44.777778  64.222222  63.777778  59.777778  57.666667   
2012-06-27 23:50:00  53.000000  64.285714  64.125000  60.875000  66.250000   
2012-06-27 23:55:00  49.555556  65.777778  65.111111  63.000000  61.666667   

                     ...     772167     769372     774204     769806  \
2012-03-01 00:00:00  ...  45.625000  65.500000  64.500000  66.428571   
2012-03-01 00:05:00  ...  50.666667  69.875000  66.666667  58.555556   
2012-03-01 00:10:00  ...  44.125000  69.000000  56.500000  59.250000   
2012-03-01 00:15:00  ...   0.000000   0.000000   0.000000   0.000000   
2012-03-01 00:20:00  ...   0.000000   0.000000   0.000000   0.000000   
...                  ...        ...        ...        ...        ...   
2012-06-27 23:35:00  ...  52.888889  69.000000  65.111111  55.666667   
2012-06-27 23:40:00  ...  54.000000  69.250000  60.125000  60.500000   
2012-06-27 23:45:00  ...  51.333333  67.888889  64.333333  57.000000   
2012-06-27 23:50:00  ...  51.125000  69.375000  61.625000  60.500000   
2012-06-27 23:55:00  ...  56.000000  67.444444  64.888889  60.888889   

                        717590     717592     717595     772168     718141  \
2012-03-01 00:00:00  66.875000  59.375000  69.000000  59.250000  69.000000   
2012-03-01 00:05:00  62.000000  61.111111  64.444444  55.888889  68.444444   
2012-03-01 00:10:00  68.125000  62.500000  65.625000  61.375000  69.857143   
2012-03-01 00:15:00   0.000000   0.000000   0.000000   0.000000   0.000000   
2012-03-01 00:20:00   0.000000   0.000000   0.000000   0.000000   0.000000   
...                        ...        ...        ...        ...        ...   
2012-06-27 23:35:00  66.333333  62.444444  66.777778  64.888889  69.666667   
2012-06-27 23:40:00  67.250000  59.375000  66.000000  61.250000  69.000000   
2012-06-27 23:45:00  66.000000  62.666667  68.666667  63.333333  67.444444   
2012-06-27 23:50:00  65.625000  66.375000  69.500000  63.000000  67.875000   
2012-06-27 23:55:00  64.222222  66.444444  68.444444  63.555556  68.666667   

                        769373  
2012-03-01 00:00:00  61.875000  
2012-03-01 00:05:00  62.875000  
2012-03-01 00:10:00  62.000000  
2012-03-01 00:15:00   0.000000  
2012-03-01 00:20:00   0.000000  
...                        ...  
2012-06-27 23:35:00  62.333333  
2012-06-27 23:40:00  62.000000  
2012-06-27 23:45:00  61.222222  
2012-06-27 23:50:0

In [9]:
df_data.values.shape
# np.save("metrla.npy", df_data.values)

(34272, 207)

In [10]:
index_list=df_data.index
index_list

DatetimeIndex(['2012-03-01 00:00:00', '2012-03-01 00:05:00',
               '2012-03-01 00:10:00', '2012-03-01 00:15:00',
               '2012-03-01 00:20:00', '2012-03-01 00:25:00',
               '2012-03-01 00:30:00', '2012-03-01 00:35:00',
               '2012-03-01 00:40:00', '2012-03-01 00:45:00',
               ...
               '2012-06-27 23:10:00', '2012-06-27 23:15:00',
               '2012-06-27 23:20:00', '2012-06-27 23:25:00',
               '2012-06-27 23:30:00', '2012-06-27 23:35:00',
               '2012-06-27 23:40:00', '2012-06-27 23:45:00',
               '2012-06-27 23:50:00', '2012-06-27 23:55:00'],
              dtype='datetime64[ns]', length=34272, freq=<pandas._libs.properties.CachedProperty object at 0x7fdd128e0700>)

In [11]:
ts=index_list[0]
ts.day
ts.hour
ts.weekday()

1

0

3

In [12]:
def encode_timestamp(ts):
    weekday_embedding=np.eye(7)[ts.weekday()].tolist()
    hour_embedding=np.eye(24)[ts.hour].tolist()
    holiday_embedding=[1.0 if ts.weekday()>4 else 0.0]
    
    embedding=weekday_embedding+hour_embedding+holiday_embedding
    return embedding

print(encode_timestamp(ts))
len(encode_timestamp(ts))

[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


32

In [13]:
embeddings=[]
for ts in index_list:
    embeddings.append(encode_timestamp(ts))
    
embeddings=np.array(embeddings)
embeddings.shape

(34272, 32)

In [15]:
time_embeddings=np.broadcast_to(embeddings[:, np.newaxis, :], (embeddings.shape[0], 207, embeddings.shape[1]))

time_embeddings.shape

(34272, 207, 32)

In [16]:
time_embeddings[0][0]
time_embeddings[100][0]
time_embeddings[0][200]
time_embeddings[100][200]

array([0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
df_se=pd.read_csv("./SE_metrla.txt", skiprows=1, index_col=[0], sep="\s+", header=None)

df_se

1         2         3         4         5         6         7   \
0                                                                           
203  1.841761 -1.151540 -0.168568 -0.325604 -0.989623  0.789932  0.859323   
181  1.371481 -1.872212  1.903371 -1.059111 -0.654879  0.782880  1.161862   
126  2.218281 -2.250492  1.111528  0.572416 -1.746900  2.243468  0.953002   
182  1.288062 -0.331109  0.197647  0.173093 -1.794996  0.634799  1.450367   
146  0.401076 -0.308793  0.164866 -0.407898 -0.168425  0.495400  0.495764   
..        ...       ...       ...       ...       ...       ...       ...   
105  1.078975 -1.185630  0.030192  0.344934 -0.365750  1.748296 -0.066169   
8    0.459705 -0.879191  0.225331 -0.227906 -1.002892 -0.169019  0.270795   
152  0.109914 -1.066517 -0.298643  0.047746 -1.099204  1.661074 -0.269183   
44   0.782809 -0.934252  0.237790 -0.437347 -1.118037  2.327020 -0.369554   
178  1.035275 -1.087167 -0.066683 -0.717801 -0.687614  1.391926  0.380868   

           8         9         10  ...        55        56        57  \
0                                  ...                                 
203  0.452492 -1.420494 -1.648759  ... -1.495561 -0.214174  0.288640   
181  0.416907 -0.613175  0.137244  ... -0.933540 -1.484988 -1.247189   
126  1.228562 -0.531206 -1.237744  ... -1.630550 -1.105467 -0.982698   
182  0.995030 -1.073426 -0.550857  ... -1.291935 -2.651067 -2.187135   
146  0.269339 -0.415135  0.059629  ... -0.273999 -0.577825 -0.640628   
..        ...       ...       ...  ...       ...       ...       ...   
105 -0.504326 -1.029582 -0.496199  ...  0.090925  0.646563 -0.694609   
8    0.779182 -0.314129 -0.051525  ... -0.620525 -1.300872 -0.922330   
152 -0.104559 -1.006560 -1.163902  ... -0.776352  0.720620 -1.317975   
44   0.212671 -0.810259 -0.624535  ... -1.147036  0.498618 -0.631112   
178 -0.092145  0.135828 -0.976485  ... -0.909916  0.278804 -0.585748   

           58        59        60        61        62        63        64  
0                                                                          
203 -0.714042  1.319986  0.644966 -0.607898 -0.916437  0.635579  2.234508  
181 -2.213340 -1.611407  0.346065 -0.780481  0.209501 -0.461250  1.381276  
126 -2.807932  1.261305  1.794437 -0.824408 -0.475096 -1.640400  2.550505  
182 -2.333035 -0.725576  1.427868 -0.234728 -1.452710 -0.499810  1.066675  
146 -0.916676 -0.267327  0.436354 -0.112321 -0.100086 -0.224527  0.522257  
..        ...       ...       ...       ...       ...       ...       ...  
105 -1.069318  0.125177 -0.494026  0.081628  0.277056 -0.474162  0.711186  
8   -1.231204 -0.137606  0.311157 -0.190977 -0.398878 -0.071213  0.140435  
152 -0.045864  0.681334  0.392876 -0.370203 -0.516546 -0.166957  0.935677  
44  -0.238238  1.025354  0.603793 -0.823943 -0.780263 -0.260537  1.316666  
178 -0.126016  0.633135 -0.397805 -0.107581  0.179408 -0.446616  1.560255  

[207 rows x 64 columns]

In [18]:
df_se.sort_index(inplace=True)

df_se

1         2         3         4         5         6         7   \
0                                                                           
0    0.281772  0.137560  0.032041  0.376998  0.119689  0.455271  0.297370   
1    0.598085 -0.658238 -0.003793  0.367317 -0.293551  0.643264  0.266016   
2    0.405826 -0.386644  0.091340  0.486498 -0.365147  0.589337  0.361405   
3    0.531393  0.046541  0.268489 -0.169185 -0.226376  0.340038  0.643024   
4    0.753611  0.141477  0.223278  0.034949 -0.558426  0.519335  0.700146   
..        ...       ...       ...       ...       ...       ...       ...   
202  0.411871 -0.240531  0.092870 -0.573618  0.349927  0.262466  0.336960   
203  1.841761 -1.151540 -0.168568 -0.325604 -0.989623  0.789932  0.859323   
204  0.421994 -0.164673  0.048039 -0.421144 -0.376481  0.475354  0.463799   
205  0.737991 -0.332271  0.498789  0.454495  0.392264 -0.085009  0.466111   
206  0.479663  0.090541  0.211308  0.237258 -0.497383  0.639257  0.654680   

           8         9         10  ...        55        56        57  \
0                                  ...                                 
0    0.062118 -0.350708  0.033635  ... -0.718249  0.111754  0.426067   
1    0.218524 -0.402583 -0.204473  ... -0.371003 -0.177085  0.011433   
2    0.116483 -0.254030 -0.350052  ... -0.762231  0.034978 -0.206282   
3    0.029763 -0.171506 -0.218548  ... -0.529749 -0.074529 -0.170860   
4    0.211131  0.017864 -0.253832  ... -0.699398 -0.202599 -0.100704   
..        ...       ...       ...  ...       ...       ...       ...   
202  0.852648 -1.108473 -0.511568  ... -0.937092  0.067185  0.097586   
203  0.452492 -1.420494 -1.648759  ... -1.495561 -0.214174  0.288640   
204  0.152236 -0.190141  0.008616  ... -0.274594 -0.872328 -0.607479   
205  0.031719 -0.133185 -0.043701  ... -0.454365  0.099454 -0.082468   
206  0.350340  0.082326 -0.535753  ... -0.219984 -0.067436  0.259047   

           58        59        60        61        62        63        64  
0                                                                          
0   -0.150170  0.118533  0.273160 -0.038722  0.149652  0.201872  0.205930  
1   -0.022771  0.065063  0.191406  0.240673 -0.481904 -0.040638  0.659682  
2   -0.240964 -0.008663  0.170174  0.405749 -0.395738  0.142042  0.920966  
3   -0.491375 -0.444542  0.367062 -0.134402 -0.630470  0.085832  0.211655  
4   -0.358003 -0.368236  0.323067 -0.155468 -0.587759  0.283558  0.144325  
..        ...       ...       ...       ...       ...       ...       ...  
202 -0.334708  0.195212  0.623012  0.187293 -0.535187 -0.652037  0.905161  
203 -0.714042  1.319986  0.644966 -0.607898 -0.916437  0.635579  2.234508  
204 -0.937983 -0.176018  0.309443  0.122353  0.116151  0.156825  0.613455  
205 -0.714835 -0.668265  0.541673 -0.378201  0.025350 -0.067997  0.719294  
206 -0.442844 -0.186043  0.308321 -0.293671 -0.661745 -0.233864  0.116894  

[207 rows x 64 columns]

In [19]:
spatial_embeddings=df_se.values

spatial_embeddings.shape

(207, 64)

In [20]:
spatial_embeddings=np.broadcast_to(spatial_embeddings[np.newaxis, :, :], (time_embeddings.shape[0], spatial_embeddings.shape[0], spatial_embeddings.shape[1]))

spatial_embeddings.shape

(34272, 207, 64)

In [22]:
data_embedded=np.concatenate((df_data.values[..., np.newaxis], spatial_embeddings, time_embeddings), axis=2)

data_embedded.shape

(34272, 207, 97)

In [23]:
np.save("./METRLA_embedded.npy", data_embedded)